# Generated by Django 4.2.6 on 2023-10-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_cms', '0002_customermodel_order_product_orderitem_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('delivering', 'DELIVERING'), ('completed', 'COMPLETED')], default='created', max_length=11),
        ),
    ]
