# Generated by Django 4.2.6 on 2023-10-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_cms', '0003_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
    ]
