# Generated by Django 4.2.6 on 2023-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_cms', '0004_rename_order_ordermodel_rename_product_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
