# Generated by Django 4.2.6 on 2023-10-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_cms', '0005_alter_customusermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='system_cms.OrderItem', to='system_cms.productmodel'),
        ),
    ]
